server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  level:
    root: info
    '[com.example.demo]': debug
  file.name: logs/debug.log
#    path: logs/debug.log
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_schema
    username: root
    password: 70111032
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true